# Generated by Django 3.0.6 on 2020-05-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='formulaire.Listing')),
            ],
        ),
    ]
