# Generated by Django 3.0.6 on 2020-05-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_auto_20200521_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Utilisateur',
        ),
        migrations.DeleteModel(
            name='Visite',
        ),
    ]
